### ISSUE TITLE
[1.12.2] Living armor giving crazy amounts of mitigation. 

### ISSUE THREAD

**Issue by VeloxAzo** [Clownvin/Living-Enchantment#10]
I'm playing the pack R.A.D. 1.2.9

I take maybe  0.5 dps in lava wearing just my boots or pants. No baubles or aether gear. No shield. 
But the chest and helm which don't have living give more reasonable reductions
Boots + pants together makes it ~0.1 dps

Pants are 9 boots are 6.

**Comment by Clownvin** [comment]
Fixed this in unreleased commit.
