### ISSUE TITLE
Rebirth of the Night Array Index error.

### ISSUE THREAD

**Issue by edenhack** [Clownvin/Living-Enchantment#15]
Rebirth of the Night modpack version: Rebirth of the Night-2.76.2
Forge: 14.23.5.2847
[crash-2020-03-30_20.47.37-server.txt](https://github.com/Clownvin/Living-Enchantment/files/4402705/crash-2020-03-30_20.47.37-server.txt)

**Comment by LemADEC** [comment]
That crash report is consided a Trojan horse by Windows defender

**Comment by democat3457** [comment]
Seems like Thorns and a rat attacking was involved. What were you doing during the crash @edenhack?
