### ISSUE TITLE
enchantments appearing as "enchantment.null" on items

### ISSUE THREAD

**Issue by mattrix444** [Clownvin/Living-Enchantment#2]
hey confirmed that when i remove this mod the vanilla enchants that were appearing on items as "enchantment.null I" etc are all back to normal i even tried adjusting the configs before but it didn't fix it only removing the mod does. thought id let you know buddy.
using all different forge versions didn't work either.

**Comment by Clownvin** [comment]
Hi, buddy! Can you please provide more information, such as:

- What version are you using
- How to replicate
- The output log

**Comment by Clownvin** [comment]
Whether or not this bug actually exists, I could never determine. Nevertheless, I am no longer updating this mod, as I'm working on a new one that's basically living enchantment but better.
