### ISSUE TITLE
[suggestion] allow items to be "knocked out"

### ISSUE THREAD

**Issue by Jackiecrazy** [Clownvin/Living-Enchantment#3]
For instance, it seems that protection from this mod isn't disappearing when Electroblob's Wizardry robes hit 0 durability. Other than screen spam, this basically means permanent immunity from damage, which is just a little balance hiccup, I'm sure. For now I've just set the growth to be extremely low, but a more permanent solution would be nice.

**Comment by Clownvin** [comment]
I'll see what I can do.

**Comment by Clownvin** [comment]
After reviewing the problem a bit more, I'm unsure exactly what you want me to do.

From the sounds of it, and after reading the source for Wizardry Robes, it seems like these robes are designed to never degrade fully, or something? Is the desired effect of this issue to just "turn off" all living effects when the item is "fully degraded", or would you like a more personal solution (I'm thinking a command that anyone can use regardless of perms which would "disable" living on the held item until repeated)

**Comment by Jackiecrazy** [comment]
The robes never break, simply turning themselves off at 0 durability. I believe silent's gems armor also never degrades fully (I know the tools don't for a fact), actually, so the option wouldn't just pertain to EB wizardry. Yes, I pretty much just would like a way to turn off living effects (specifically the extra protection) at 0 durability. I can also see something like decreasing living effectiveness at lower durabilities making sense (the tool/armor is weak from wear and tear, and can't help you as much), and it also incentivizes repairing the item. Something like the final effectiveness of the item being multiplied by the durability percentage would be good for that purpose.

**Comment by Clownvin** [comment]
Hi, I'm going to incorporate this as a new feature in the mod based on this mod. It's basically the same mod, but with the potential to affect more than just items. 

I'm going to close this problem, as I don't plan to update this soon-to-be obsolete version anymore.
