### ISSUE TITLE
Only one Item gain EXP

### ISSUE THREAD

**Issue by DirtyNative** [Clownvin/Living-Enchantment#7]
If I put Living on my chestplate and also on my pickaxe, only the Chestplate get experience when killing mobs / dismantle blocks. I think this is a bug

I disabled experience by orbs, instead the items gain exp by doing their job.

I am using Minecraft version 1.12.2 in combination with forge and optifine

**Comment by Clownvin** [comment]
There are a few XP sharing settings, maybe fiddle with those. I'm about to launch a 3.2.2 build, so I'll see if I can recreate/solve it now.

**Comment by Clownvin** [comment]
Couldn't really reproduce this. Closing for now.
